name: Deploy Preview

on:
  push:
    branches: [preview]

jobs:
  deploy-vercel:
    name: Trigger Vercel Preview Build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy Hook
        run: curl -X POST "${{ secrets.VERCEL_PREVIEW_DEPLOY_HOOK }}"
